class TaskError(Exception):
    pass


class TaskAlreadyExists(TaskError):
    pass
